### ISSUE TITLE
Срефакторить исключения в прошлых задачах

### ISSUE THREAD

**Issue by Allyonzy** [Maxim-Ishenko/JAVA_innopolis#12]
После изучения темы про исключения, рекомендую срефакторить код. Работать не с самим Exception, а с его наследниками. Там, где нужно, добавить свои исключения. Подумать во всех ли сеттерах нужны исключения
Если будете вносить  изменения, то создать ветку refactoring/exceptions и коммитить в неё

**Comment by Maxim-Ishenko** [comment]
https://github.com/Maxim-Ishenko/JAVA_innopolis/pull/15

**Comment by Maxim-Ishenko** [comment]
In accordance with approved PR https://github.com/Maxim-Ishenko/JAVA_innopolis/pull/15
